name: Archive Repository into Release
on: 
  push:
    tags:
      - "spark-archive-*"
jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Exit if not on main/master
        run: |
          chmod +x "./.github/verify-source.sh"
          "./.github/verify-source.sh"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            "*.md"
            "*.MD"