name: Archive Repository into Release
on: 
  push:
    tags:
      - "spark-archive-*"
jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Exit if not on main/master
        run: |
          function verify_source {
          if git branch $1 --contains $GITHUB_REF | grep -q $1; then
              return 0
          else
              return -1
          fi
          }

          if verify_source "main" || verify_source "master"; then
          exit 0
          else
          # Didn't come from master or main
          exit -1
          fi
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            "*.md"
            "*.MD"